name: Run Unit Tests.

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  setup-and-build:
    name: Setup repository and compile source code.

    # Run on each specified operating system.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so job can access it.
      - uses: actions/checkout@v2

      - name: Update GNU Make  on MacOS
        if: matrix.os == 'macos-latest'
        run: brew install --with-default-names make

      - name: Set up repository.
        run: |
          make -v
          make setup

      - name: Compile tests.
        run: make tests CFLAGS=-fPIC

  run-tests:
    name: Run Unit Tests.
    needs: setup-and-build

    # Run on each specified operating system.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so job can access it.
      - uses: actions/checkout@v2

      - name: Run all Unit Tests.
        run: make run-tests

  memcheck-tests:
    name: Check for memory leaks.
    needs: setup-and-build

    # Run on each specified operating system.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so job can access it.
      - uses: actions/checkout@v2

      - name: Check for memory leaks using valgrind.
        run: make valgrind-tests
